version: "3.8"

services:
  passnet-user:
    image: tony16019/passnet-user:latest
    container_name: passnet-user
    environment:
      - ENV=development
      - SERVER_PORT=8080
      - GRPC_PORT=7070
      - GRPC_SAGA_HOST=passnet-user-saga
      - GRPC_SAGA_PORT=6160
    ports:
      - "8080:8080"
      - "7070:7070"
    networks:
      - passnet-network

  passet-user-saga:
    image: tony16019/passnet-user-saga:latest
    container_name: passnet-user-saga
    environment:
      - PROFILE=prod
      - USER_SERVICE_GRPC_HOST=passnet-user
      - USER_SERVICE_GRPC_PORT=7070
      - USER_SAGA_PORT=6160
    ports:
      - "6160:6160"
    networks:
      - passnet-network

networks:
  passnet-network:
    driver: bridge
