spring:
  application:
    name: passnet-user-saga
  config:
    import: optional:configserver:http://v1-LoadBala-1SP0U9QHHZM0-c5b28a8b8c85decf.elb.us-east-1.amazonaws.com:8080
grpc:
  client:
    user-service:
      address: 'static://${USER_SERVICE_GRPC_HOST}:${USER_SERVICE_GRPC_PORT}'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
  server:
    port: ${USER_SAGA_PORT}