spring:
  application:
    name: passnet-user-saga
  config:
    import: optional:configserver:http://localhost:9999
grpc:
  client:
    user-service:
      address: 'static://localhost:7071'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
  server:
    port: 6160