spring:
  application:
    name: passnet-organizer-saga
  kafka:
    consumer:
      group-id: passnet_organizer_saga_group
grpc:
  client:
    organizer-service:
      address: 'static://127.0.0.1:7074'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
  server:
    port: 6164