spring:
  kafka:
    bootstrap-server: http://20.69.120.200:9092
    bootstrap-servers:
      - http://20.69.120.200:9092
    properties:
      schema.registry.url: http://20.69.120.200:8081
      specific.avro.reader: true
    consumer:
      group-id: classroom_saga_group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    template:
      default-topic:
grpc:
  port: 6566
  main-service:
    host: localhost
    port: 50051