spring:
  application:
    name: passnet-classroom-saga
  kafka:
    consumer:
      group-id: passnet_classroom_saga_group
grpc:
  server:
    port: 6163
  client:
    classroom-service:
      address: 'static://localhost:7073'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext