spring:
  kafka:
    producer:
      bootstrap-servers: http://52.148.184.202:9092
      topics:
        post-new-job-event: post-new-job-event
        accept-student-application-event: accept-student-application-event
        remove-student-application-event: remove-student-application-event
        delete-job-event: delete-job-event
    properties:
      schema-registry-url: http://52.148.184.202:8081
grpc:
  port: 6565
  main-service:
    host: passnet-recruitment-service
    port: 9090