spring:
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      topics:
        post-new-job-event: ${TOPIC_POST_NEW_JOB_EVENT}
        accept-student-application-event: ${TOPIC_ACCEPT_STUDENT_APPLICATION_EVENT}
        remove-student-application-event: ${TOPIC_REMOVE_STUDENT_APPLICATION_EVENT}
        delete-job-event: ${TOPIC_DELETE_JOB_EVENT}
    properties:
      schema-registry-url: ${KAFKA_SCHEMA_REGISTRY_URL}
grpc:
  port: ${GRPC_PORT_LISTENER}
  main-service:
    host: ${MAIN_SERVICE_GRPC_HOST}
    port: ${MAIN_SERVICE_GRPC_PORT}