spring:
  application:
    name: passnet-recruitment-saga
grpc:
  server:
    port: 6162
  client:
    recruitment-service:
      address: 'static://localhost:7072'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext